version: '3.5'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    volumes:
      - ${PWD}:/app
    working_dir: /app
    depends_on:
      - postgres